name: chatlympus
description: Chat with the Olympus
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.0.0
  timeago: ^3.1.0

  #base project
  get: ^4.6.5
  dio: ^5.2.1
  intl: ^0.18.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.4.0
  shared_preferences: ^2.0.17
  google_fonts: ^4.0.3
  pretty_dio_logger: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

